#!/usr/bin/env bash

# init-hydroshare
# HydroShare container intiliaization script
# Author: Michael Stealey <michael.j.stealey@gmail.com>

sleep 3s
cp /hydroshare/hydroshare.conf /etc/supervisor/conf.d/hydroshare.conf
userdel hydro-service \
 && groupdel storage-hydro \
 && echo "storage-hydro:x:0:" >> /etc/group \
 && echo "hydro-service:x:0:0::/hydroshare:/bin/bash" >> /etc/passwd \
 && chown -R hydro-service:storage-hydro /hydroshare /hs_tmp /shared_tmp /tmp \
 && chmod -R 3777 /hs_tmp /shared_tmp /tmp 

python manage.py runserver 0.0.0.0:8000
