# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-17 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import theme.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0032_auto_20210607_2027'),
    ]

    operations = [
        # START(ID=357,NAME=MigrationAlterFieldPictureOnCommunity,TYPE=ALTER,OBJECTS=[Community])
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=theme.utils.get_upload_path_community),
        ),
        # END(ID=357)
        # START(ID=358,NAME=MigrationAlterFieldPictureOnGroupAccess,TYPE=ALTER,OBJECTS=[GroupAccess])
        migrations.AlterField(
            model_name='groupaccess',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=theme.utils.get_upload_path_group),
        ),
        # END(ID=358)
    ]
