# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_access_control', '0034_resourceaccess_allow_private_sharing'),
    ]

    operations = [
        # START(ID=360,NAME=MigrationAddFieldRequiresExplanationOnGroupAccess,TYPE=ALTER,OBJECTS=[GroupAccess])
        migrations.AddField(
            model_name='groupaccess',
            name='requires_explanation',
            field=models.BooleanField(default=False, editable=False, help_text='whether membership requests include explanation'),
        ),
        # END(ID=360)
        # START(ID=361,NAME=MigrationAddFieldExplanationOnGroupMembershipRequest,TYPE=ALTER,OBJECTS=[GroupMembershipRequest])
        migrations.AddField(
            model_name='groupmembershiprequest',
            name='explanation',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        # END(ID=361)
    ]
