name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: canopyiq/python-dind-builder:latest
    services:
      open-tel:
        image: baseshiftefraim/otelcol:latest
        ports:
          - 4317:4317
    steps:
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set Up Docker
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          echo "c" | ./local-dev-first-start-only.sh
      - name: Run Tests
        run: |
          docker-compose -f local-dev.yml up 
          export BASEGUARD_TOKEN=2b02ce1b-9b5c-4e75-8ff9-ddb562944734 
          export BASEGUARD_RUN=$(dubhub baseguard create_run --orgToken 2b02ce1b-9b5c-4e75-8ff9-ddb562944734 --projectUuid 75294a4c-9e1f-4dfa-a5db-aa56e40ac5ab))
          ./hsctl managepy test  
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          PR_REF: ${{ github.event.pull_request.head.sha }}

# dubhub baseguard upload_schema --orgToken 2b02ce1b-9b5c-4e75-8ff9-ddb562944734 
# dubhub baseguard analyse --orgToken 2b02ce1b-9b5c-4e75-8ff9-ddb562944734
